# Site settings
title: kevin的个人博客
email: iverson_10@163.com
description: > #kevin的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevinzhang1986.github.io/index.html" # the base hostname & protocol for your site

# Paginate（分页）
#gems: [jekyll-paginate]
# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
#highlighter: pygments
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: kevin zhang
  email: iverson_10@gmail.com
  link: http://kevinzhang1986.github.io/
  github: https://github.com/kevinzhang1986
  github_username: kevinzhang1986


locals:                                     #自定义常量
  tags: 标签
  about: 关于
  active: 技术总结                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址

# 头像
avatar: /assets/image/favicon.ico
# avatar: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/favicon.ico
# 网站CSS路径
css: /assets/css/
# css: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/css/
# 网站JS路径
js: /assets/js/
# js: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/js/
# 网站图片路径
image: /assets/image/
# image: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/

# disqus 设置
disqus:
  shortname: kevin
